FROM python:3.4-alpine

ENV USER=nonroot

RUN apk update && \
    ## Upgrade OS packages
    apk upgrade && \
    apk add curl \
        sudo

## Setup a non-root user in ALpine
RUN adduser -D $USER \
        && echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USER \
        && chmod 0440 /etc/sudoers.d/$USER

#Run Container as nonroot
USER nonroot