# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: container-cicd-workflow

on: push

env:
  CONTAINER_REGISTRY: sbacrdemo.azurecr.io  # set this to Container Registry name
  DOCKERFILE: Dockerfile_vulnerable

jobs:
  container-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
              
   ## Authentication
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    ## Build The Docker Image
    - run: |
        echo "github.sha=$GITHUB_SHA"
        docker build -t ${{ env.CONTAINER_REGISTRY }}/scanning-demo:${{ github.sha }} . -f ${{ env.DOCKERFILE }}

    ## Scan the Docker Image
    - uses: Azure/container-scan@v0 
      name: Scan image for vulnerabilities
      id: container-scan
      continue-on-error: true
      with:
        image-name: ${{ env.CONTAINER_REGISTRY }}/scanning-demo:${{ github.sha }} 

    ## Publish the Docker Images
    - name: Publish
      run: |
        docker push ${{ env.CONTAINER_REGISTRY }}/scanning-demo:${{ github.sha }}

    ## Publish Telemetry to App Insights
    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }} 
       
    